version: "3.0"
services: 
  db:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: DBTEST
      MYSQL_USER: tux
      MYSQL_PASSWORD: test1234

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: tux
      WORDPRESS_DB_PASSWORD: test1234
      WORDPRESS_DB_NAME: DBTEST